[package]
name = "nugletapi"
version = "0.1.0"
authors = ["J. Cliff Dyer <jcd@sdf.org>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
http = "0.1"
rusqlite = { version = "*", features = ["serde_json"] }
serde = "1"
serde_derive = "1"
serde_json = "*"
